# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/caesar.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(250, 30, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.key = QtWidgets.QLabel(self.centralwidget)
        self.key.setGeometry(QtCore.QRect(160, 230, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.key.setFont(font)
        self.key.setObjectName("key")
        self.plain_text = QtWidgets.QLabel(self.centralwidget)
        self.plain_text.setGeometry(QtCore.QRect(50, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.plain_text.setFont(font)
        self.plain_text.setObjectName("plain_text")
        self.ciphertext = QtWidgets.QLabel(self.centralwidget)
        self.ciphertext.setGeometry(QtCore.QRect(20, 320, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.ciphertext.setFont(font)
        self.ciphertext.setObjectName("ciphertext")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(250, 130, 451, 41))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(250, 230, 451, 41))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(250, 320, 451, 121))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.decrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.decrypt_btn.setGeometry(QtCore.QRect(560, 470, 141, 41))
        self.decrypt_btn.setObjectName("decrypt_btn")
        self.encrypt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.encrypt_btn.setGeometry(QtCore.QRect(250, 470, 141, 41))
        self.encrypt_btn.setObjectName("encrypt_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "CAESAR CIPHER"))
        self.key.setText(_translate("MainWindow", "Key:"))
        self.plain_text.setText(_translate("MainWindow", "Plain Text:"))
        self.ciphertext.setText(_translate("MainWindow", "Cipher Text:"))
        self.decrypt_btn.setText(_translate("MainWindow", "Decrypt"))
        self.encrypt_btn.setText(_translate("MainWindow", "Encrypt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
